### PR TITLE
Untitled

### PR DESCRIPTION
**Pull request by lamp**
Hey All, I made this so merb_datamapper will work with datamapper at least up until 1.0.2.

### CODE REVIEW

**Comment by namelessjon** [comment]
What does this patch add?  DataMapper is happy accepting a hash of options, so I'm not sure what about these classes is needed for compatibility with 1.0.2.  But perhaps I am missing something, so please explain!

On a more technical note, your construction of the uri seems quite unsafe. I strongly suspect it will break in the case of a password containing @ or / (and perhaps more characters).  In addition, there should be no need to require rubygems (i.e. if the user is using rubygems, they’ll have required it higher up the stack and if they have not, there’s probably a good reason for this).

**Comment by dkubb** [comment]
I'd recommend using Addressable::URI.new to construct the URI, and then call #normalize and #to_s on the resulting object, or just #to_s. This will ensure that every component is properly escaped, and in the case of #normalize, redundant components will be eliminated. I would much rather trust the library (that we already use elsewhere) to construct URls than to use string concatenation.

**Comment by namelessjon** [comment]
I still don't quite see the purpose of this patch?  Using addressable is an improvement, but this is now the steps the configuration will take:

in merb_datamapper:
1. hash is converted to symbol keys
2. hash is converted to uri
3. uri is converted to string

then in DataMapper.setup()
1. string is parsed to uri.
2. uri is converted to hash
3. hash is converted to mash (with string/symbol indifferent keys)

What am I missing?

**Comment by dkubb** [comment]
Oh, I was just commenting on that one specific piece of code. I haven't looked over the entire patch yet, so @lamp will need to comment there.

EDIT: fwiw, I would generally prefer to see as few transformations between different types of objects as possible. If a Hash/Mash can be passed around, that's probably better.

**Comment by lamp** [comment]
The reason for submitting this patch is due to dm not dealing with the default merb configuration for an sqlite database.

If you have 

development:
  adapter:  sqlite3
  database: foo.db

datamapper will not connect to that database, but rather (I assume) create an in memory sqlite database, which is obviously non standard behaviour. This doesn't seem to be an issue for non merb users as I was unable to find a fix, however it is an issue for me.

I agree that there should be as few object transformations as possible, if there is another way of fixing this then please do.

**Comment by lamp** [comment]
Oh, I did update the gem to use addressable as dkubb pointed out it is a much better way of building the url.

**Comment by namelessjon** [comment]
Hmmm.  This seems to be a combination of two issues.  The first is in merb_datamapper, and can be solved with a simple `if sqlite3 then sqlite`.  The second seems to be a problem with the sqlite adapter in DataMapper.  I'm talking in #datamapper atm.

**Comment by namelessjon** [comment]
The `:path`/`:database` issue has now been fixed upstream, which should be available in the next release of DataMapper (1.1.0) which is currently on rc2.  If you want to refine the pull request to correct sqlite3 to sqlite, then I will merge that.  I don't think the full uri processing is needed.

**Comment by ngollan** [comment]
Is this still an issue? Current git master passes its specs with DM 1.1.0, so if there is still a problem, I'd appreciate a spec that demonstrates failing and wanted behaviour, and possibly a rebased and squashed patch.

**Comment by namelessjon** [comment]
The DataMapper side of this (`:path` vs. `:database` key issue) is fixed in the current release of DataMapper.

The sqlite/sqlite3 is still an issue.

**Pull request closed without merging**
